# Generated by Django 2.2.11 on 2020-03-19 15:02

import MovieCRUD.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviesintheaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=4)),
                ('genres', djongo.models.fields.ArrayField(model_container=MovieCRUD.models.genre)),
                ('ratings', djongo.models.fields.ArrayField(model_container=MovieCRUD.models.Rating)),
                ('poster', models.CharField(max_length=120)),
                ('contentRating', djongo.models.fields.ArrayField(model_container=MovieCRUD.models.contentRate)),
                ('duration', models.CharField(max_length=120)),
                ('releaseDate', models.CharField(max_length=120)),
                ('averageRating', models.IntegerField(blank=True, default=None, null=True)),
                ('storyline', models.CharField(max_length=120)),
                ('actors', djongo.models.fields.ArrayField(model_container=MovieCRUD.models.actor)),
                ('imdbRating', models.FloatField()),
                ('posterurl', models.CharField(max_length=120)),
            ],
        ),
    ]
