# Generated by Django 2.2.11 on 2020-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesintheaters',
            name='storyline',
            field=models.TextField(),
        ),
    ]
