# Generated by Django 2.2.11 on 2020-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCRUD', '0002_auto_20200319_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesintheaters',
            name='posterurl',
            field=models.CharField(max_length=200),
        ),
    ]
