# Generated by Django 2.2.11 on 2020-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCRUD', '0003_auto_20200319_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesintheaters',
            name='averageRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
